// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfflineService.proto

#ifndef PROTOBUF_INCLUDED_OfflineService_2eproto
#define PROTOBUF_INCLUDED_OfflineService_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_OfflineService_2eproto 

namespace protobuf_OfflineService_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_OfflineService_2eproto
namespace ik_OfflineService {
class ReadOfflineRequest;
class ReadOfflineRequestDefaultTypeInternal;
extern ReadOfflineRequestDefaultTypeInternal _ReadOfflineRequest_default_instance_;
class ReadOfflineResponse;
class ReadOfflineResponseDefaultTypeInternal;
extern ReadOfflineResponseDefaultTypeInternal _ReadOfflineResponse_default_instance_;
class WriteOfflineRequest;
class WriteOfflineRequestDefaultTypeInternal;
extern WriteOfflineRequestDefaultTypeInternal _WriteOfflineRequest_default_instance_;
}  // namespace ik_OfflineService
namespace google {
namespace protobuf {
template<> ::ik_OfflineService::ReadOfflineRequest* Arena::CreateMaybeMessage<::ik_OfflineService::ReadOfflineRequest>(Arena*);
template<> ::ik_OfflineService::ReadOfflineResponse* Arena::CreateMaybeMessage<::ik_OfflineService::ReadOfflineResponse>(Arena*);
template<> ::ik_OfflineService::WriteOfflineRequest* Arena::CreateMaybeMessage<::ik_OfflineService::WriteOfflineRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ik_OfflineService {

// ===================================================================

class WriteOfflineRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ik_OfflineService.WriteOfflineRequest) */ {
 public:
  WriteOfflineRequest();
  virtual ~WriteOfflineRequest();

  WriteOfflineRequest(const WriteOfflineRequest& from);

  inline WriteOfflineRequest& operator=(const WriteOfflineRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WriteOfflineRequest(WriteOfflineRequest&& from) noexcept
    : WriteOfflineRequest() {
    *this = ::std::move(from);
  }

  inline WriteOfflineRequest& operator=(WriteOfflineRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WriteOfflineRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WriteOfflineRequest* internal_default_instance() {
    return reinterpret_cast<const WriteOfflineRequest*>(
               &_WriteOfflineRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WriteOfflineRequest* other);
  friend void swap(WriteOfflineRequest& a, WriteOfflineRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WriteOfflineRequest* New() const final {
    return CreateMaybeMessage<WriteOfflineRequest>(NULL);
  }

  WriteOfflineRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WriteOfflineRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WriteOfflineRequest& from);
  void MergeFrom(const WriteOfflineRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WriteOfflineRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 friendid = 1;
  void clear_friendid();
  static const int kFriendidFieldNumber = 1;
  ::google::protobuf::int32 friendid() const;
  void set_friendid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ik_OfflineService.WriteOfflineRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 friendid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_OfflineService_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReadOfflineRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ik_OfflineService.ReadOfflineRequest) */ {
 public:
  ReadOfflineRequest();
  virtual ~ReadOfflineRequest();

  ReadOfflineRequest(const ReadOfflineRequest& from);

  inline ReadOfflineRequest& operator=(const ReadOfflineRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReadOfflineRequest(ReadOfflineRequest&& from) noexcept
    : ReadOfflineRequest() {
    *this = ::std::move(from);
  }

  inline ReadOfflineRequest& operator=(ReadOfflineRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadOfflineRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadOfflineRequest* internal_default_instance() {
    return reinterpret_cast<const ReadOfflineRequest*>(
               &_ReadOfflineRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ReadOfflineRequest* other);
  friend void swap(ReadOfflineRequest& a, ReadOfflineRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReadOfflineRequest* New() const final {
    return CreateMaybeMessage<ReadOfflineRequest>(NULL);
  }

  ReadOfflineRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReadOfflineRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReadOfflineRequest& from);
  void MergeFrom(const ReadOfflineRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadOfflineRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 userid = 1;
  void clear_userid();
  static const int kUseridFieldNumber = 1;
  ::google::protobuf::int32 userid() const;
  void set_userid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ik_OfflineService.ReadOfflineRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 userid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_OfflineService_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReadOfflineResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ik_OfflineService.ReadOfflineResponse) */ {
 public:
  ReadOfflineResponse();
  virtual ~ReadOfflineResponse();

  ReadOfflineResponse(const ReadOfflineResponse& from);

  inline ReadOfflineResponse& operator=(const ReadOfflineResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReadOfflineResponse(ReadOfflineResponse&& from) noexcept
    : ReadOfflineResponse() {
    *this = ::std::move(from);
  }

  inline ReadOfflineResponse& operator=(ReadOfflineResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadOfflineResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadOfflineResponse* internal_default_instance() {
    return reinterpret_cast<const ReadOfflineResponse*>(
               &_ReadOfflineResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ReadOfflineResponse* other);
  friend void swap(ReadOfflineResponse& a, ReadOfflineResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReadOfflineResponse* New() const final {
    return CreateMaybeMessage<ReadOfflineResponse>(NULL);
  }

  ReadOfflineResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReadOfflineResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReadOfflineResponse& from);
  void MergeFrom(const ReadOfflineResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadOfflineResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes chat_msgs = 1;
  int chat_msgs_size() const;
  void clear_chat_msgs();
  static const int kChatMsgsFieldNumber = 1;
  const ::std::string& chat_msgs(int index) const;
  ::std::string* mutable_chat_msgs(int index);
  void set_chat_msgs(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_chat_msgs(int index, ::std::string&& value);
  #endif
  void set_chat_msgs(int index, const char* value);
  void set_chat_msgs(int index, const void* value, size_t size);
  ::std::string* add_chat_msgs();
  void add_chat_msgs(const ::std::string& value);
  #if LANG_CXX11
  void add_chat_msgs(::std::string&& value);
  #endif
  void add_chat_msgs(const char* value);
  void add_chat_msgs(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& chat_msgs() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_chat_msgs();

  // @@protoc_insertion_point(class_scope:ik_OfflineService.ReadOfflineResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> chat_msgs_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_OfflineService_2eproto::TableStruct;
};
// ===================================================================

class OfflineServiceRpc_Stub;

class OfflineServiceRpc : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline OfflineServiceRpc() {};
 public:
  virtual ~OfflineServiceRpc();

  typedef OfflineServiceRpc_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void WriteOffline(::google::protobuf::RpcController* controller,
                       const ::ik_OfflineService::WriteOfflineRequest* request,
                       ::google::protobuf::Empty* response,
                       ::google::protobuf::Closure* done);
  virtual void ReadOffline(::google::protobuf::RpcController* controller,
                       const ::ik_OfflineService::ReadOfflineRequest* request,
                       ::ik_OfflineService::ReadOfflineResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OfflineServiceRpc);
};

class OfflineServiceRpc_Stub : public OfflineServiceRpc {
 public:
  OfflineServiceRpc_Stub(::google::protobuf::RpcChannel* channel);
  OfflineServiceRpc_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~OfflineServiceRpc_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements OfflineServiceRpc ------------------------------------------

  void WriteOffline(::google::protobuf::RpcController* controller,
                       const ::ik_OfflineService::WriteOfflineRequest* request,
                       ::google::protobuf::Empty* response,
                       ::google::protobuf::Closure* done);
  void ReadOffline(::google::protobuf::RpcController* controller,
                       const ::ik_OfflineService::ReadOfflineRequest* request,
                       ::ik_OfflineService::ReadOfflineResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OfflineServiceRpc_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WriteOfflineRequest

// int32 friendid = 1;
inline void WriteOfflineRequest::clear_friendid() {
  friendid_ = 0;
}
inline ::google::protobuf::int32 WriteOfflineRequest::friendid() const {
  // @@protoc_insertion_point(field_get:ik_OfflineService.WriteOfflineRequest.friendid)
  return friendid_;
}
inline void WriteOfflineRequest::set_friendid(::google::protobuf::int32 value) {
  
  friendid_ = value;
  // @@protoc_insertion_point(field_set:ik_OfflineService.WriteOfflineRequest.friendid)
}

// bytes msg = 2;
inline void WriteOfflineRequest::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WriteOfflineRequest::msg() const {
  // @@protoc_insertion_point(field_get:ik_OfflineService.WriteOfflineRequest.msg)
  return msg_.GetNoArena();
}
inline void WriteOfflineRequest::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ik_OfflineService.WriteOfflineRequest.msg)
}
#if LANG_CXX11
inline void WriteOfflineRequest::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ik_OfflineService.WriteOfflineRequest.msg)
}
#endif
inline void WriteOfflineRequest::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ik_OfflineService.WriteOfflineRequest.msg)
}
inline void WriteOfflineRequest::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ik_OfflineService.WriteOfflineRequest.msg)
}
inline ::std::string* WriteOfflineRequest::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:ik_OfflineService.WriteOfflineRequest.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WriteOfflineRequest::release_msg() {
  // @@protoc_insertion_point(field_release:ik_OfflineService.WriteOfflineRequest.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WriteOfflineRequest::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:ik_OfflineService.WriteOfflineRequest.msg)
}

// -------------------------------------------------------------------

// ReadOfflineRequest

// int32 userid = 1;
inline void ReadOfflineRequest::clear_userid() {
  userid_ = 0;
}
inline ::google::protobuf::int32 ReadOfflineRequest::userid() const {
  // @@protoc_insertion_point(field_get:ik_OfflineService.ReadOfflineRequest.userid)
  return userid_;
}
inline void ReadOfflineRequest::set_userid(::google::protobuf::int32 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:ik_OfflineService.ReadOfflineRequest.userid)
}

// -------------------------------------------------------------------

// ReadOfflineResponse

// repeated bytes chat_msgs = 1;
inline int ReadOfflineResponse::chat_msgs_size() const {
  return chat_msgs_.size();
}
inline void ReadOfflineResponse::clear_chat_msgs() {
  chat_msgs_.Clear();
}
inline const ::std::string& ReadOfflineResponse::chat_msgs(int index) const {
  // @@protoc_insertion_point(field_get:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  return chat_msgs_.Get(index);
}
inline ::std::string* ReadOfflineResponse::mutable_chat_msgs(int index) {
  // @@protoc_insertion_point(field_mutable:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  return chat_msgs_.Mutable(index);
}
inline void ReadOfflineResponse::set_chat_msgs(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  chat_msgs_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ReadOfflineResponse::set_chat_msgs(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  chat_msgs_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ReadOfflineResponse::set_chat_msgs(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  chat_msgs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
inline void ReadOfflineResponse::set_chat_msgs(int index, const void* value, size_t size) {
  chat_msgs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
inline ::std::string* ReadOfflineResponse::add_chat_msgs() {
  // @@protoc_insertion_point(field_add_mutable:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  return chat_msgs_.Add();
}
inline void ReadOfflineResponse::add_chat_msgs(const ::std::string& value) {
  chat_msgs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
#if LANG_CXX11
inline void ReadOfflineResponse::add_chat_msgs(::std::string&& value) {
  chat_msgs_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
#endif
inline void ReadOfflineResponse::add_chat_msgs(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  chat_msgs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
inline void ReadOfflineResponse::add_chat_msgs(const void* value, size_t size) {
  chat_msgs_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ik_OfflineService.ReadOfflineResponse.chat_msgs)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ReadOfflineResponse::chat_msgs() const {
  // @@protoc_insertion_point(field_list:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  return chat_msgs_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ReadOfflineResponse::mutable_chat_msgs() {
  // @@protoc_insertion_point(field_mutable_list:ik_OfflineService.ReadOfflineResponse.chat_msgs)
  return &chat_msgs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ik_OfflineService

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_OfflineService_2eproto
